### ISSUE TITLE
Quick Setup 获取镜像失败

### ISSUE THREAD

**Issue by Lieke2333** [tellery/tellery#106]
**Describe the bug**
获取镜像失败

**To Reproduce**
1、使用 docker 安装案例，进行到docker-compose up时无法拉取镜像
`% docker-compose up

WARNING: The EMIAL_PORT variable is not set. Defaulting to a blank string.
WARNING: The EMIAL_HOST variable is not set. Defaulting to a blank string.
WARNING: The EMIAL_FROM variable is not set. Defaulting to a blank string.
Pulling redis (redis:6.2.4)...
ERROR: Head https://registry-1.docker.io/v2/library/redis/manifests/6.2.4: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fredis%3Apull&service=registry.docker.io: EOF`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17562650/125192363-0a340180-e27a-11eb-8826-58b7884b38e7.png)
**Desktop (please complete the following information):**
 - OS: [e.g. MacOS ]
 

**Additional context**

**Comment by Lieke2333** [comment]
尝试修改为国内镜像地址，失败

**Comment by domechn** [comment]
这应该是国内网络的问题。我自己关了代理 `docker pull redis` 时也有相同的问题。如果可以的话，建议你使用代理

> 尝试修改为国内镜像地址，失败

用的是哪个镜像地址呢？

**Comment by Lieke2333** [comment]
谢谢，已经换了几个国内的镜像地址，勉强下载下来了~
