### ISSUE TITLE
Any way to run just the editor?

### ISSUE THREAD

**Issue by armaandh** [tellery/tellery#135]
Really like the amazing editor you built (Notion-like editor). Wondering if there's a way to run just the editor alone? For example, as an npm package that has the self contained editor.

**Comment by cosformula** [comment]
Hey armaandh, we are grateful for your attention. 

We may not open-source a standalone editor at present, Tellery is in the early stage of development and there is still a lot of work to do. The editor is tightly coupled with the other parts of tellery, it will take a lot of effort to separate.

We also noticed that Outline is [archiving their standalone editor repo](https://github.com/outline/rich-markdown-editor/discussions/481), which makes us more cautious to make decisions.
