### ISSUE TITLE
node-cache-manager is not used correctly

### ISSUE THREAD

**Issue by domechn** [tellery/tellery#228]
**Describe the bug**

When using pg, the cache cannot be shared when there are multiple backend instances.

As a result, online users cannot be aggregated and counted in socket services.

**Additional context**

The reason for this problem is that no external cache is used when using `node-cache-manager`.

https://github.com/tellery/tellery/blob/258269983986d49521b6c18e598113224f1da1e1/packages/api/src/utils/cache.ts#L24-L26

ps: there is currently no implementation of the `node-cache-manager` with postgresql.

**Comment by raycursive** [comment]
After careful consideration, we decided that if one wanna deploy multiple backend instances to balance load or achieve high availability, a redis for state storage must be deployed as well. That is, the memory cache will be only used for a single backend instance in this scenario (w.r.t. socket service)

Later a config of `deployMode` will be introduced to check if such a agreement is violated.
