### ISSUE TITLE
Is it possible to connect Clickhouse database? 

### ISSUE THREAD

**Issue by kravtsovd** [tellery/tellery#271]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by onesuper** [comment]
We do have a plan to support a seires of open-source OLAP engines, such as Presto/Trino and Clickhouse, etc. You can subcribe our newsletter to get the updates on our [website](https://tellery.io/) in the future.

Also welcome to contribute to our [community-supported connectors project](https://github.com/tellery/community-supported-connectors).

**Comment by hooopo** [comment]
Is MySQL source support on roadmap?
