### ISSUE TITLE
UnauthorizedError: not exist - After deploying through docker

### ISSUE THREAD

**Issue by singla-ds** [tellery/tellery#324]
**Describe the bug**
After following the steps mentioned in GitHub to deploy Tellery locally, I am getting UnauthorizedError: not exist error every time even after clean installtion. 

tellery-server_1                    |   <-- GET /
tellery-server_1                    |   xxx GET / 401 33ms -
tellery-server_1                    | UnauthorizedError: not exist
tellery-server_1                    |     at Function.notExist (/tellery/dist/src/error/error.js:46:16)
tellery-server_1                    |     at UserService.verifyToken (/tellery/dist/src/services/user.js:154:45)
tellery-server_1                    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
tellery-server_1                    |     at async user (/tellery/dist/src/middlewares/user.js:23:23)
tellery-server_1                    |     at async logger (/tellery/node_modules/koa-logger/index.js:67:7)
tellery-server_1                    |     at async error (/tellery/dist/src/middlewares/error.js:5:9) {
tellery-server_1                    |   status: 401
tellery-server_1                    | }
tellery-server_1                    |   <-- GET /favicon.ico
tellery-server_1                    |   xxx GET /favicon.ico 401 6ms -
tellery-server_1                    | UnauthorizedError: not exist
tellery-server_1                    |     at Function.notExist (/tellery/dist/src/error/error.js:46:16)
tellery-server_1                    |     at UserService.verifyToken (/tellery/dist/src/services/user.js:154:45)
tellery-server_1                    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
tellery-server_1                    |     at async user (/tellery/dist/src/middlewares/user.js:23:23)
tellery-server_1                    |     at async logger (/tellery/node_modules/koa-logger/index.js:67:7)
tellery-server_1                    |     at async error (/tellery/dist/src/middlewares/error.js:5:9) {
tellery-server_1                    |   status: 401

And if I go to http://localhost:8000/ I get {"errMsg":"not exist"}

**To Reproduce**
1. Go to installation directory and docker-compose up.
2. See error

**Expected behavior**
Expect to run on local server smoothly

**Screenshots**
![image](https://user-images.githubusercontent.com/65246103/131944230-55b40afb-5d47-402c-8db9-07eaa485a200.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2 (Intel i7)
 - Browser: Chrome
 - Version: 92

**Comment by raycursive** [comment]
Hi singla-ds, thanks for your bug reporting!

Have you ever deployed an earlier version of Tellery locally?

It might be tricky to do a "clean installation" within the context of docker-compose,

you can try the following

```
docker-compose rm -f && docker image rm -f compose_tellery-init compose_tellery-server
docker volume rm -f compose_pg_data compose_redis_data
```

Then try to go with `docker-compose up` again to see if it works.

If the error appears again, just let me know!

**Comment by singla-ds** [comment]
Hi @raycursive 

Tried above command. Some images and volumes were removed. Got following error. Had to remove tellery/connector and tellery/tellery image manually

![image](https://user-images.githubusercontent.com/65246103/131953295-35238ed8-051d-46ca-9f4e-f377e4d2ddd7.png)

After this ran docker-compose up
Still getting the same error

![image](https://user-images.githubusercontent.com/65246103/131954429-046647e7-1824-4e9c-93df-3ebc3c09e4e2.png)


![image](https://user-images.githubusercontent.com/65246103/131954454-3b7c9ad4-baa9-42cf-8e8b-d565531e0206.png)


Does having other docker containers/images impact tellery? All other containers are stopped though

**Comment by raycursive** [comment]
Oh I got it. The browser holds the cookies `x-user-token` generated from your first deployment.
Since you re-deployed it, tokens are regenerated and hence invalid.

Just clear the cookies or starts from an incognito window, it will work well.

If you are using Chrome, just right click -> Application -> Storage -> Clear site data (with Cookies checked)

This is actually our fault for not considering corner cases clearly. This problem will be fixed soon.

**Comment by singla-ds** [comment]
Thanks this worked
