### ISSUE TITLE
What editor used under the hood?

### ISSUE THREAD

**Issue by marek-baranowski** [tellery/tellery#348]
Hi, I was curious what editor was used for text editing (like DraftJS, CKEditor, or Prosemirror etc.) but couldn't find anything that would give me the clue. Was the Tellery editor write from scratch?

**Comment by cosformula** [comment]
Hi, thanks for asking. 
Yes, the Tellery editor is written from scratch, we investigated these frameworks at the start, but none of these fit our needs.

**Comment by marek-baranowski** [comment]
Thanks for clarification! That's impressive as writing text editor from scratch is a huge challange. The result is great, it works wonderfully. Wondering what were that functionalities that prevented you from using any of those editors :)

**Comment by cosformula** [comment]
Most open-sourced editors are a single content editable element, which is great for just text editing, but when it comes to tables, visualizations, and other embed resources, editing non-text area using native selecting and the cursor would be annoying.

Inspired by Notion, we think a block-styled editor is what we need for a modern doc. Compared to other editors, each block is an independent content editable element, [editorjs](https://editorjs.io/) did the same thing if you are interested.

Avoid using content editable attribute also makes developing new features easy, as they are independent of each other, and some of them don't need content editable at all, we can use React to create blocks and rendering. Many open-sourced editors can't do that.

**Comment by marek-baranowski** [comment]
This is a very interesing insight. Thank you for comprehensive answer!
